project_id = "jhcbvppqhmedikzuwats"

[functions.create-character-sheet]
verify_jwt = true

[functions.generate-story-with-character]
verify_jwt = true

[functions.get-story-details]
verify_jwt = true
