-- Delete the 30 characters that were just added
DELETE FROM public.character_sheets 
WHERE name IN (
  'Whiskers the Cat',
  'Buddy the Dog',
  'Hoppy the Rabbit', 
  'Bruno the Bear',
  'Ellie the Elephant',
  'Leo the Lion',
  'Foxy the Fox',
  'Panda Po',
  'Luna the Unicorn',
  'Draco the Dragon',
  'Fairy Belle',
  'Robo Max',
  'Captain Bot',
  'Captain Hook',
  'Sailor Sam',
  'Super Star',
  'Thunder Boy',
  'Princess Rose',
  'Queen Elsa',
  'Friendly Monster',
  'Fluffy Monster',
  'Merlin the Wise',
  'Luna the Witch',
  'Alien Zorg',
  'Astro Girl',
  'Cookie the Baker',
  'Pizza Pete',
  'Nemo the Fish',
  'Shelly the Crab',
  'Stella the Star',
  'Benny the Bee',
  'Rocky the Dinosaur'
);