// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhcbvppqhmedikzuwats.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoY2J2cHBxaG1lZGlrenV3YXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzcyMDUsImV4cCI6MjA3MjgxMzIwNX0.mT88OwWTxYeZgS5JcErfDbazdepFPQtOeTCYTm89tRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});